[package]
name = "ilbal"
version = "0.1.1"
edition = "2024"
repository = "https://github.com/ilbal-dev/ilbal-cli"
authors = ["ilbal.dev"]

[package.metadata.wix]
upgrade-guid = "9C0377AD-932C-4D2B-9A71-1F6A7BE49B5E"
path-guid = "596A288D-3E56-4B20-9EAB-9A0705103766"
license = false
eula = false

[dependencies]
anyhow = "1.0.103"
clap = { version = "4.6.1", features = ["cargo"] }
colored = "3.1.1"
dialoguer = "0.12.0"
indicatif = "0.18.4"
indoc = "2.0.7"
owo-colors = { version = "4.3.0", features = ["supports-color", "supports-colors"] }
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.8.22"
thiserror = "2.0.18"
walkdir = "2.5.0"
include_dir = { version = "0.7.4", features = ["glob"] }
console = "0.16.4"
figlet-rs = "1.0.0"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
