services:
  postgresql:
    image: codeberg.org/ilbal/ilbal-postgresql:latest
    pull_policy: missing
    container_name: example-postgresql
    hostname: example-postgresql
    restart: unless-stopped
    environment:
      POSTGRES_USER: duck
      POSTGRES_PASSWORD: quack123
      POSTGRES_DB: app
    ports:
      - "33330:5432"
    command: ["postgres", "-c", "config_file=/postgres/postgresql.conf"]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/postgres/postgresql.conf:ro
      - ./postgres/pg_hba.conf:/postgres/pg_hba.conf:ro
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - example
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U duck -d app"]
      interval: 10s
      timeout: 2s
      retries: 10
      start_period: 30s
      start_interval: 1s

  pgadmin4:
    image: docker.io/dpage/pgadmin4:latest
    pull_policy: missing
    container_name: example-pgadmin4
    hostname: example-pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: duck@duck.com
      PGADMIN_DEFAULT_PASSWORD: quack123
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "33331:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin4/servers.json:/pgadmin4/servers.json
      - ./pgadmin4/pgpass:/pgadmin4/pgpass
    networks:
      - example
    depends_on:
      postgresql:
        condition: service_healthy

  pgdog:
    image: ghcr.io/pgdogdev/pgdog:latest
    pull_policy: missing
    container_name: example-pgdog
    hostname: example-pgdog
    restart: unless-stopped
    ports:
      - "33332:6432"
    volumes:
      - ./pgdog/pgdog.toml:/pgdog/pgdog.toml
      - ./pgdog/users.toml:/pgdog/users.toml
    networks:
      - example
    depends_on:
      postgresql:
        condition: service_healthy

  sequin-redis:
    image: docker.io/library/redis:latest
    pull_policy: missing # could be `always`, too
    container_name: example-redis
    hostname: example-redis
    restart: unless-stopped
    ports:
      - "33334:6379"
    command: ["redis-server", "--port", "6379"]
    volumes:
      - sequin_redis_data:/data
    networks:
      - example

  sequin:
    image: docker.io/sequin/sequin:latest
    pull_policy: missing # could be `always`, too
    container_name: example-sequin
    hostname: example-sequin
    restart: unless-stopped
    environment:
      - PG_HOSTNAME=example-postgresql
      - PG_DATABASE=app
      - PG_PORT=5432
      - PG_USERNAME=duck
      - PG_PASSWORD=quack123
      - PG_POOL_SIZE=20
      # Un-comment for SSL
      # - PG_SSL=true
      - SECRET_KEY_BASE=wDPLYus0pvD6qJhKJICO4dauYPXfO/Yl782Zjtpew5qRBDp7CZvbWtQmY0eB13If
      - VAULT_KEY=2Sig69bIpuSm2kv0VQfDekET2qy8qUZGI8v3/h3ASiY=
      - REDIS_URL=redis://example-redis:6379
      - CONFIG_FILE_PATH=/config/sequin.yml
    ports:
      - "33333:7376"
    volumes:
      - ./sequin/sequin.yml:/config/sequin.yml
    networks:
      - example
    depends_on:
      postgresql:
        condition: service_healthy
      sequin-redis:
        condition: service_started

volumes:
  pgdata:
  pgadmin_data:
  sequin_redis_data:

networks:
  example:
    driver: bridge
